Componentes III: Detalle de libros
wolox-training/mapo-react-native pull request #28
Opened 2018-09-28 00:58 UTC by mpujolWolox

## Description
- Componentes III: Detalle de libros

## Screenshoots
![04](https://user-images.githubusercontent.com/42747134/46182126-9c1c1c80-c28f-11e8-9eb5-24fc3e2b7e90.gif)
![03](https://user-images.githubusercontent.com/42747134/46182127-9c1c1c80-c28f-11e8-92d6-faeed8e114ff.gif)
![Uploading 02.gif…]()
![Uploading 01.gif…]()

## Trello Card
- https://trello.com/c/YuOXMOVc

2018-09-28 20:10 UTC, wfolini requested changes

2018-09-28 20:10 UTC, WFolini commented on react-native/training/src/app/screens.js
> +    },
Delete `Home` tabNavigator

2018-09-28 20:10 UTC, WFolini commented on react-native/training/src/app/screens/BookDetails/index.js
> +import React, { Component } from 'react';
`BookDetails` is a child screen of `Dummy` screen. Move it to `src/app/screens/Dummy/screens/BookDetails`

2018-10-01 15:55 UTC, wfolini approved these changes

2018-10-01 15:55 UTC, merged